name: Build go microservice
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-docker:
    name: Publish docker image
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: m2stacklab/go-bar-microservice:latest